version: '3.7'
services: 
   nginx: 
     image: nginx:latest
     container_name: production_nginx
     ports:
       - target: 80 
         published: 80
     container_name: nginx
     depends_on:
       - react
     volumes: 
       - type: bind
         source: ./nginx.conf
         target: /etc/nginx/nginx.conf

   mysql: 
    image: mysql:5.7
    environment: 
      MYSQL_DATABASE: independentproject
      MYSQL_ROOT_PASSWORD: password
    ports:
       - target: 3306
         protocol: tcp
    container_name: mysql

   backend:
    container_name: backend
    image: api
    build: .
    ports:
      - target: 8081
        protocol: tcp
    depends_on:
      - mysql

   react: 
    container_name: frontend
    image: react
    build: ./Independentprojectfrontend
    ports: 
      - target: 3000
        protocol: tcp 
    depends_on:
      -  backend
